# Generated by Django 5.2.5 on 2025-12-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_student_enrollment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.schedule'),
        ),
        migrations.AddField(
            model_name='student',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='train_line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
