# Generated by Django 5.2.5 on 2025-10-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='building',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
