import React  from "react";
import "../styles/About.css";
import { Link } from "react-router-dom";

function About(){
    return(
        <div className="main">
            <div className="about-menu">  
                <ul>
                    <Link to="/Home">
                        <li>Home</li>
                    </Link> 
                    <Link>
                        <li>Login</li>
                    </Link>
                </ul>
            </div>
            <div className="how-to">
                <h1>How to use this website</h1>
                <h2>1. Sign Up for an account</h2>
                <h2>2. Download your UIC schedule .ics 
                    <p>
                        <a href="calendar-info">Learn how to get an ics calendar</a></p></h2>
                <h2>3. Login to your account on the <Link to="/Login">Login</Link> page</h2>
                <h2>4. Upload your schedule and pick one schedule from the schedule dropdown
                </h2>
                <h2>5.Pick the station you will arrive at</h2>
                <h2>6.Pick your train line</h2>
                <h2>7.Pick your departure station</h2>
                <h2>8.Click on the generate schedule button
                    <h3>You should be able to see the schedule generated by the algorithm</h3>
                </h2>
                <h2>9. See your matches by clicking the Matches button 
                    <p><a href="matches-info">Learn what Matches are</a></p>
                </h2>
            </div>
            <div className="calendar-info">
                <h1>What is an .ics file?</h1>
                <h2>An ICS file is a universal calendar file that stores event information like date, 
                    time, and location in a plain-text format, allowing it to be shared between 
                    different calendar applications such as Google Calendar, Outlook, and Apple Calendar. 
                    It acts as a digital invitation or event package that can be easily imported into a user's
                     calendar by double-clicking the file or using an import function</h2>
                <h1>How to get your .ics file?</h1>
                <h2>1.Go to your my uic portal</h2>
                <img src="../myuicportalHome.png" alt="uic portal Home page"/>
                <h2>2.Go to your XE Registration</h2>
                <img src="../myuicportalViewRegistration.png" alt="uic portal XE Registration"/>
                <h2>3.Click on 'View registration information'</h2>
                <img src="../myuicportalViewRegistration2.png" alt="uic portal view Registration"/>
                <h2>4.In the 'Look up a schedule' tab, select your desired term</h2>
                <img src="../myuicportalLookUp.png" alt="uic portal Look Up Tab"/>
                <h2>5.Click on the calendar icon and save the file on your desktop (or desired folder)</h2>
                <img src="../myuicportalScheduleIcon.png" alt="uic portal schedule Icon"/>
                <h2>6.Upload this file on the Home page</h2>
            </div>
            <div className="matches-info">
                <h1>What are Matches?</h1>
                <h2>Our algorithm calculates the people matching your schedule so you can connect 
                    with them and travel together.
                </h2>
            </div>
        </div>
    )
}

export default About;